# Generated by Django 4.1 on 2022-08-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Extra"),
                            (2, "Low"),
                            (3, "Mid"),
                            (4, "High"),
                            (5, "Urgent"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("doing", models.BooleanField(default=False)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
